name: Fortify AST Scan

# Customize trigger events based on your DevSecOps process and/or policy
on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '19 14 * * 2'
  workflow_dispatch:

jobs:
  Fortify-AST-Scan:
    # Use the appropriate runner for building your source code. Ensure dev tools required to build your code are present and configured appropriately (MSBuild, Python, etc).
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v4

      # Java is required to run the various Fortify utilities. Ensuring proper version is installed on the runner.
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Perform SAST scan
        uses: fortify/github-action/setup@main
        with:
           export-path: false
           fcli: action-default
        env:
            SSC_URL: ${{secrets.SSC_URL}}                          #http://13.209.176.153:8080/ssc/                             # SSC URL
            SSC_TOKEN: ${{secrets.SSC_TOKEN}}                       #f9672e49-8bcc-4123-bb8b-19be432cd9fd                        # SSC CIToken or AutomationToken
            SC_SAST_TOKEN: ${{secrets.SC_SAST_TOKEN}}                    # ScanCentral SAST client auth token
            SC_SAST_SENSOR_VERSION: ${{secrets.SC_SAST_SENSOR_VERSION}}          #24.2.0.0150
            SSC_APPVERSION: ${{secrets.SSC_APPVERSION}}                   #61

      - name: Perform SAST Login
        uses: fortify/github-action/internal/sc-sast-login@main

      - name: Perform SAST package
        uses: fortify/github-action/package@main

      - name: Perform SAST package
        uses: fortify/github-action/internal/run@main
        with:
            cmd: '"${FCLI_CMD}" sc-sast scan start --publish-to "${SSC_APPVERSION}" -p package.zip -v "${SC_SAST_SENSOR_VERSION}" --store sc_sast_scan'

      - name: Perform SAST run
        uses: fortify/github-action/internal/run@main
        if: env.DO_WAIT == 'true' || env.DO_EXPORT == 'true'
        with:
           cmd: '"${FCLI_CMD}" sc-sast scan wait-for ::sc_sast_scan::'

      - name: Perform SAST logout
        uses: fortify/github-action/internal/sc-sast-logout@main
        if: env.DO_EXPORT == 'true'

      - name: Perform SAST ssc-export
        uses: fortify/github-action/ssc-export@main





