name: Fortify AST Scan

# Customize trigger events based on your DevSecOps process and/or policy
on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '19 14 * * 2'
  workflow_dispatch:

jobs:
  Fortify-AST-Scan:
    # Use the appropriate runner for building your source code. Ensure dev tools required to build your code are present and configured appropriately (MSBuild, Python, etc).
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v4

      # Java is required to run the various Fortify utilities. Ensuring proper version is installed on the runner.
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      # Perform SAST and optionally SCA scan via Fortify on Demand/Fortify Hosted/Software Security Center, then
      # optionally export SAST results to the GitHub code scanning dashboard. In case further customization is
      # required, you can use sub-actions like fortify/github-action/setup@v1 to set up the various Fortify tools
      # and run them directly from within your pipeline; see https://github.com/fortify/github-action#readme for
      # details.
      - name: Run FoD SAST Scan
        uses: fortify/github-action@a92347297e02391b857e7015792cd1926a4cd418
        with:
          sast-scan: true
        env:
          ### Required configuration when integrating with Fortify on Demand
          #FOD_URL: https://ams.fortify.com
          #FOD_TENANT: ${{secrets.FOD_TENANT}}
          #FOD_USER: ${{secrets.FOD_USER}}
          #FOD_PASSWORD: ${{secrets.FOD_PAT}}
          ### Optional configuration when integrating with Fortify on Demand
          # EXTRA_PACKAGE_OPTS: -oss                       # Extra 'scancentral package' options, like '-oss'' if
                                                           # Debricked SCA scan is enabled on Fortify on Demand
          # EXTRA_FOD_LOGIN_OPTS: --socket-timeout=60s     # Extra 'fcli fod session login' options
          # FOD_RELEASE: MyApp:MyRelease                   # FoD release name, default: <org>/<repo>:<branch>; may
                                                           # replace app+release name with numeric release ID
          # DO_WAIT: true                                  # Wait for scan completion, implied if 'DO_EXPORT: true'
          # DO_EXPORT: true                                # Export SAST results to GitHub code scanning dashboard
          ### Required configuration when integrating with Fortify Hosted / Software Security Center & ScanCentral
           SSC_URL: http://13.209.176.153:8080/ssc/                            # SSC URL
           SSC_TOKEN: f9672e49-8bcc-4123-bb8b-19be432cd9fd                        # SSC CIToken or AutomationToken
           SC_SAST_TOKEN: 21977cab-5180-4420-91cf-9f70a98bf732                # ScanCentral SAST client auth token
           SC_SAST_SENSOR_VERSION: 24.2.0.0150 # Sensor version on which to run the scan;
                                                                     # usually defined as organization or repo variable
          ### Optional configuration when integrating with Fortify Hosted / Software Security Center & ScanCentral
          # EXTRA_SC_SAST_LOGIN_OPTS: --socket-timeout=60s # Extra 'fcli sc-sast session login' options
           SSC_APPVERSION: 61                # SSC application version, default: <org>/<repo>:<branch>
          # EXTRA_PACKAGE_OPTS: -bv myCustomPom.xml        # Extra 'scancentral package' options
          # DO_WAIT: true                                  # Wait for scan completion, implied if 'DO_EXPORT: true'
          # DO_EXPORT: true                                # Export SAST results to GitHub code scanning dashboard

      - name: Perform SAST scan
        uses: fortify/github-action/setup@main
        with:
           export-path: false
           fcli: action-default
      - name: Perform SAST Login
        uses: fortify/github-action/internal/sc-sast-login@main
      - name: Perform SAST package
        uses: fortify/github-action/package@main
      - name: Perform SAST package
        uses: fortify/github-action/internal/run@main
        with:
            cmd: '"${FCLI_CMD}" sc-sast scan start --publish-to "${SSC_APPVERSION}" -p package.zip -v "${SC_SAST_SENSOR_VERSION}" --store sc_sast_scan'
      - name: Perform SAST run
        uses: fortify/github-action/internal/run@main
        if: env.DO_WAIT == 'true' || env.DO_EXPORT == 'true'
        with:
           cmd: '"${FCLI_CMD}" sc-sast scan wait-for ::sc_sast_scan::'
      - name: Perform SAST logout
        uses: fortify/github-action/internal/sc-sast-logout@main
        if: env.DO_EXPORT == 'true'
      - name: Perform SAST ssc-export
        uses: fortify/github-action/ssc-export@main

branding:
icon: 'shield'
color: 'blue'





